"""empty message

Revision ID: 6a39cb59db55
Revises: 3773dc777af3
Create Date: 2016-11-15 00:01:09.044157

"""

# revision identifiers, used by Alembic.
revision = '6a39cb59db55'
down_revision = '3773dc777af3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'is_author',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('comment', sa.Column('author_name', sa.String(length=80), nullable=True))
    op.drop_constraint(u'comment_ibfk_1', 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    op.alter_column('post', 'live',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'live',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('comment', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'comment_ibfk_1', 'comment', 'author', ['author_id'], ['id'])
    op.drop_column('comment', 'author_name')
    op.alter_column('author', 'is_author',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
